Repository depromeet/ddoeat_client, pull requests merged in 2023-12, with the labels that each got.

#7 #6 useDebounce 훅 생성
  src/common/hooks/useDebounce.tsx
Labels: feat

#17 디렉토리 구조 변경
  src/app/layout.tsx
  src/components/PostItem.tsx
  src/components/common/QueryClientProvider/index.tsx
  src/hooks/useGetPost.ts
  tsconfig.json
Labels: chore

#22 ? 유틸리티 클래스 작성
  tailwind.config.ts
Labels: feat, style

#15 테일윈드 컬러 추가
  tailwind.config.ts
Labels: feat, style

#27 TextArea 컴포넌트 작성 및 폰트 설정
  .eslintrc.json
  .pnp.cjs
  .vscode/settings.json
  package.json
  src/app/fonts/NanumSquareRoundB.woff2
  src/app/fonts/NanumSquareRoundEB.woff2
  src/app/fonts/NanumSquareRoundL.woff2
  src/app/fonts/NanumSquareRoundR.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/TextArea/index.tsx
  src/hooks/useDebounce.tsx
  tailwind.config.ts
  yarn.lock
Labels: feat, style

#28 Input 컴포넌트 작성
  src/components/common/Input/index.tsx
  src/hooks/useInput.ts
Labels: feat

#35 TextArea 컴포넌트 디자인 수정사항 반영
  src/components/common/TextArea/index.tsx
Labels: feat, style

#31 feat: NavigationButton 컴포넌트 작성
  public/assets/appleLogo.svg
  public/assets/kakaoLogo.svg
  src/components/common/CTAButton/index.tsx
Labels: feat

#45 #44 style: body-14-extraBold 추가
  src/app/globals.css
Labels: style

#47 Button 컴포넌트 추상화
  src/components/common/Button/index.tsx
  src/components/common/CTAButton/index.tsx
Labels: feat, refactor

#29 맛집 컴포넌트 작성
  public/assets/icon/More.svg
  public/assets/img/search/store.png
  src/app/globals.css
  src/components/common/VisitNumberFlag.tsx
  src/components/search/store/index.tsx
Labels: feat

#43 Feat/#42 feat: StoreDetailLog 컴포넌트 생성
  public/rectangle_mock_img.png
  src/components/StoreDetail/StoreDetailLog/index.tsx
Labels: feat
