Repository depromeet/ddoeat_client, pull requests merged in 2024-04, with the labels that each got.

#315 피드 컴포넌트 작성
  .pnp.cjs
  .yarn/cache/@tailwindcss-line-clamp-npm-0.4.4-23cb911440-3d2ad992aa.zip
  package.json
  public/assets/icon24/right_arrow_24.svg
  public/assets/image/hamburger.jpeg
  src/app/feed/detail/[id]/layout.tsx
  src/app/feed/detail/[id]/page.tsx
  src/app/feed/regist/complete/page.tsx
  src/app/feed/regist/page.tsx
  src/app/test/page.tsx
  src/components/common/Header/index.tsx
  src/components/feed/Feed/FeedContainer.tsx
  src/components/feed/Feed/FeedDate.tsx
  src/components/feed/Feed/FeedDescription.tsx
  src/components/feed/Feed/FeedDetailDescription.tsx
  src/components/feed/Feed/FeedImage.tsx
  src/components/feed/Feed/FeedProfile.tsx
  src/components/feed/Feed/index.tsx
  src/components/main/WriteLogButton/index.tsx
  src/components/mypage/MyPageFeed/MyPageFeedContainer.tsx
  src/components/mypage/MyPageFeed/MyPageFeedImage.tsx
  src/components/mypage/MyPageFeed/MyPageFeedStoreInfo.tsx
  src/components/mypage/MyPageFeed/index.tsx
  src/components/review/ImageUploader/index.tsx
  src/hooks/api/useGetFeedDetail.ts
  src/hooks/api/usePostFeed.ts
  tailwind.config.ts
  yarn.lock
Labels: feat

#319 Feat/#318 바텀 네비게이션 리팩토링
  public/assets/icon24/add_feed_24.svg
  public/assets/icon24/feed_24.svg
  public/assets/icon24/home_24.svg
  public/assets/icon24/profile_default_24.svg
  src/app/page.tsx
  src/app/share/[id]/page.tsx
  src/components/common/BottomNavigation/index.tsx
  src/components/common/Icon/index.tsx
  src/components/main/AddStoreButton/index.tsx
  src/components/main/BottomNavigation/index.tsx
  src/components/main/BottomSheet/components/BottomSheetShowContent.tsx
  src/components/main/CurrentLocationButton/index.tsx
  src/components/main/ProfileButton/index.tsx
  src/constants/navigation.ts
Labels: refactor

#322 Feature/#320
  next.config.js
  src/app/feed/detail/[id]/page.tsx
  src/app/feed/layout.tsx
  src/app/feed/page.tsx
  src/app/test/page.tsx
  src/components/feed/Feed/FeedImage.tsx
  src/components/feed/Feed/FeedProfile.tsx
  src/components/main/StorePreviewSection/StoreLogPhotoPreview.tsx
  src/components/main/StorePreviewSection/index.tsx
  src/hooks/api/useGetFeedDetail.ts
  src/hooks/api/useGetFeedList.ts
  src/hooks/api/useGetStore.ts
  src/types/feed.ts
  src/utils/parser.ts
Labels: feat

#328 #325 fix: BottomNavigation fix
  src/app/feed/detail/[id]/page.tsx
  src/app/feed/page.tsx
  src/components/common/BottomNavigation/index.tsx
  src/constants/navigation.ts
Labels: fix

#331 #330 feat: follow layout api call 수정
  src/app/follow/[id]/layout.tsx
  src/app/follow/[id]/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/hooks/api/useGetUserProfile.ts
Labels: fix

#329 프로필 페이지
  public/assets/icon22/profile_edit_button_22.svg
  public/assets/icon24/profile_none_24.svg
  src/app/feed/regist/complete/page.tsx
  src/app/follow/[id]/page.tsx
  src/app/page.tsx
  src/app/profile/[id]/layout.tsx
  src/app/profile/[id]/page.tsx
  src/components/mypage/MyLogContent/index.tsx
  src/components/profile/BookMarkContent/index.tsx
  src/components/profile/BookmarkItem/index.tsx
  src/components/profile/FollowingButton/index.tsx
  src/components/profile/Log/index.tsx
  src/components/profile/MyPageFeed/MyPageFeedContainer.tsx
  src/components/profile/MyPageFeed/MyPageFeedImage.tsx
  src/components/profile/MyPageFeed/MyPageFeedStoreInfo.tsx
  src/components/profile/MyPageFeed/index.tsx
  src/components/profile/ProfileFeedContent/index.tsx
  src/components/profile/Tab/TabContent.tsx
  src/components/profile/Tab/TabGroup.tsx
  src/components/profile/Tab/TabHeader.tsx
  src/components/profile/Tab/TabItem.tsx
  src/components/profile/Tab/index.tsx
  src/hooks/api/useGetMyUserId.ts
  src/hooks/api/useInfiniteBookMark.ts
  src/hooks/api/useInfiniteGetProfileFeed.ts
  src/hooks/api/usePatchFollow.ts
  src/hooks/api/usePutProfileImage.ts
  src/utils/auth.ts
Labels: feat
