Repository depromeet/ddoeat_client, pull requests merged in 2024-01, with the labels that each got.

#32 Feat/#25 마이페이지 로그 컴포넌트 생성
  public/assets/img/LogImage.svg
  public/assets/img/default_star_24.svg
  public/assets/img/filled_star_24.svg
  src/components/Log/index.tsx
  src/components/common/MenuTypeFlag.tsx
  src/components/common/StarScore/index.tsx
Labels: feat

#69 #66 SearchField 컴포넌트 작성
  src/components/common/SearchField/index.tsx
Labels: feat

#56 #55 로그인 페이지 작성
  src/app/login/page.tsx
Labels: feat

#40 Tab 컴포넌트 작성
  src/components/common/Tab/TabContent.tsx
  src/components/common/Tab/TabGroup.tsx
  src/components/common/Tab/TabHeader.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/common/Tab/index.tsx
  tailwind.config.ts
Labels: feat

#54 #52 스토어 컴포넌트 리팩토링
  public/assets/icon/More.svg
  public/assets/image/LogImage.svg
  public/assets/image/search/store.png
  public/assets/img/default_star_24.svg
  public/assets/img/filled_star_24.svg
  src/api/useDeleteLog.ts
  src/components/Log/index.tsx
  src/components/StoreDetail/StoreDetailLog/index.tsx
  src/components/common/ImageUploader/index.tsx
  src/components/common/StarScore/index.tsx
  src/components/review/StarRating/index.tsx
  src/components/search/store/index.tsx
Labels: refactor

#57 #53 BottomNavigation 컴포넌트 작성
  public/assets/icon16/plus_16.svg
  src/components/common/BottomNavigation/AddStoreButton/index.tsx
  src/components/common/BottomNavigation/index.tsx
Labels: feat

#62 약관 페이지, 약관 관련 컴포넌트, 헤더 컴포넌트 작성
  public/assets/icon24/checkbox_default_24.svg
  src/app/terms/layout.tsx
  src/app/terms/page.tsx
  src/components/common/Header/index.tsx
  src/components/terms/AllTermsCheckBox/index.tsx
  src/components/terms/NavigationButton/index.tsx
  src/components/terms/TermsItem/index.tsx
  src/constants/terms.ts
  tailwind.config.ts
  tsconfig.json
Labels: feat

#64 #51 FloatingButton 컴포넌트 작성
  public/assets/icon24/loction_default_24.svg
  src/components/Home/CurrentLocation/index.tsx
  src/components/Home/FloatingButton/index.tsx
  tailwind.config.ts
Labels: feat

#72 #67 Report 컴포넌트 작성
  public/assets/ddobab/ddobab_report_1.svg
  public/assets/ddobab/ddobab_report_2.svg
  src/components/StoreDetail/Report/index.tsx
Labels: feat

#74 #73 ImageContainer 컴포넌트 작성
  src/components/common/ImageContainer/index.tsx
Labels: feat

#70 #68 feat: Tag 컴포넌트 생성
  src/components/common/Tag/index.tsx
Labels: feat

#78 #77 전체 레이아웃 작성 및 BottomSheet Container 작성
  src/app/layout.tsx
  src/components/common/AnimatePortal/index.tsx
  src/components/common/BottomSheet/components/BottomSheetWrapper.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Portal/index.tsx
Labels: feat

#86 #85 style: small tag width style 조정
  src/components/common/Tag/index.tsx
Labels: style, refactor

#92 #80 카카오맵 세팅
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.23.7-9691b86096-eba85bd24d.zip
  .yarn/cache/kakao.maps.d.ts-npm-0.1.39-333b43bbc2-b89c3ee7d6.zip
  .yarn/cache/react-kakao-maps-sdk-npm-1.1.24-e5d9082d74-2a555a76af.zip
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/hooks/useLocation.ts
  tsconfig.json
  yarn.lock
Labels: feat

#96 env 타입 지정
  .eslintrc.json
  src/app/layout.tsx
  src/env.d.ts
  tsconfig.json
Labels: fix

#98 Report 컴포넌트 분리
  public/assets/ddobab/ddobab_report_1.svg
  src/components/StoreDetail/Report/ReVisit.tsx
  src/components/StoreDetail/Report/ReportContainer.tsx
  src/components/StoreDetail/Report/TopVisit.tsx
  src/components/StoreDetail/Report/index.tsx
Labels: feat, refactor

#65 Feat/#59 Pin 버튼 컴포넌트 생성
  public/assets/icon20/pin_visitor_20.svg
  public/assets/icon30/polygon_30.svg
  public/assets/icon56/bookmark_56.svg
  src/app/globals.css
  src/components/common/Pin/Marker.tsx
  src/components/common/Pin/PinBubble.tsx
  src/components/common/Pin/PinIcon.tsx
  src/components/common/Pin/index.tsx
  src/constants/motions.ts
  tailwind.config.ts
Labels: feat

#75 #71 feat: StarScore 별점 나눠진 거 반영
  public/assets/icon24/star20_24.svg
  public/assets/icon24/star40_24.svg
  public/assets/icon24/star50_24.svg
  public/assets/icon24/star60_24.svg
  src/components/common/StarScore/StarByRating/index.tsx
  src/components/common/StarScore/index.tsx
Labels: feat, refactor

#94 #93 헤더 컴포넌트 className 추가
  public/assets/icon24/left_arrow_24.svg
  src/components/common/Header/index.tsx
Labels: feat

#81 BottomNavigation 좌우 버튼 추가
  public/assets/icon24/profile_default_24.svg
  public/assets/icon24/profile_filled_24.svg
  src/components/Home/AddStoreButton/index.tsx
  src/components/Home/BottomNavigation/index.tsx
  src/components/Home/FloatingButton/index.tsx
  src/components/Home/ProfileButton/index.tsx
  src/components/common/BottomNavigation/index.tsx
Labels: feat

#105 #104 CurrentLocationMarker 분리
  src/app/page.tsx
  src/components/main/BottomNavigation/index.tsx
  src/components/main/CurrentLocationButton/index.tsx
  src/components/main/CurrentLocationMarker/index.tsx
  src/hooks/useCoordinate.ts
  src/hooks/useLocation.ts
  src/types/map.ts
Labels: feat, refactor

#83 검색 페이지 작성
  public/assets/ddobab/ddobab_sad.svg
  public/assets/ddobab/ddobab_spoon.svg
  src/api/api-config.ts
  src/api/useGetStoreList.ts
  src/app/search/page.tsx
  src/components/common/Input/index.tsx
  src/components/common/ListItem/index.tsx
  src/components/common/NoSearchResult/index.tsx
  src/components/common/VisitNumberFlag.tsx
  src/components/main/LogItem/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
  src/components/mypage/BookmarkItem/index.tsx
  src/components/search/SearchItem/index.tsx
  src/components/search/SearchTopBar/index.tsx
  src/components/search/store/index.tsx
  src/hooks/useGetPost.ts
Labels: feat

#107 #106 BottomNavigation 적용
  src/app/page.tsx
  src/components/common/Button/index.tsx
  src/components/main/AddStoreButton/index.tsx
  src/components/main/BottomNavigation/index.tsx
  src/components/main/CurrentLocationButton/index.tsx
  src/components/main/ProfileButton/index.tsx
  src/hooks/useCoordinate.ts
  src/hooks/useThrottle.ts
Labels: feat

#97 리뷰 페이지 작성
  src/app/review/[storeId]/layout.tsx
  src/app/review/[storeId]/page.tsx
  src/app/review/page.tsx
  src/app/search/page.tsx
  src/components/common/Header/index.tsx
  src/components/review/ImageUploader/index.tsx
  src/components/review/StarRating/index.tsx
  src/hooks/api/useGetStoreList.ts
  src/hooks/api/usePostLog.ts
Labels: feat

#112 #111 중심좌표 변경 throttle ms 수정
  src/app/page.tsx
  src/components/main/CurrentLocationButton/index.tsx
  src/hooks/useCoordinate.ts
Labels: fix

#116 Feat/#114 MyLog 컴포넌트 수정
  src/components/common/ListItem/index.tsx
  src/components/common/MenuTypeFlag.tsx
  src/components/common/StarScore/index.tsx
  src/components/mypage/Log/index.tsx
Labels: style, refactor

#120 #113 FilterTagList 컴포넌트 작성 및 적용
  .pnp.cjs
  .yarn/cache/@csstools-selector-specificity-npm-3.0.1-bd7a5961fc-e4b5aac3bd.zip
  .yarn/cache/postcss-nesting-npm-12.0.2-9daab2658d-41701bff41.zip
  .yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-57decb9415.zip
  package.json
  postcss.config.js
  public/assets/icon20/food_beer_active_20.svg
  public/assets/icon20/food_beer_default_20.svg
  public/assets/icon20/food_cafe_active_20.svg
  public/assets/icon20/food_cafe_default_20.svg
  public/assets/icon20/food_chinese_active_20.svg
  public/assets/icon20/food_chinese_default_20.svg
  public/assets/icon20/food_japanese_active_20.svg
  public/assets/icon20/food_japanese_default_20.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Tag/index.tsx
  src/components/main/FilterTagList/FilterTagItem.tsx
  src/components/main/FilterTagList/index.tsx
  src/constants/tags.ts
  src/types/tag.ts
  yarn.lock
Labels: feat

#115 #108 최근검색어 기능 구현
  public/assets/icon12/close_12.svg
  public/assets/icon24/close_solid_24.svg
  src/app/review/[storeId]/layout.tsx
  src/app/review/[storeId]/page.tsx
  src/app/search/page.tsx
  src/components/common/Header/index.tsx
  src/components/common/ListItem/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
  src/components/mypage/Log/index.tsx
  src/components/search/RecentSearchKeyword/index.tsx
  src/components/search/SearchItem/index.tsx
  src/components/search/SearchTopBar/index.tsx
  src/hooks/api/useDeleteLog.ts
  src/hooks/api/useGetStoreList.ts
  src/hooks/useInput.ts
  src/hooks/useIsMounted.ts
  src/utils/parser.ts
  src/utils/useStorageState.ts
Labels: feat, refactor

#122 리뷰 작성 페이지 작성
  public/assets/icon20/pencil_20.png
  src/api/api-config.ts
  src/api/query-config.ts
  src/app/review/[[...storeId]]/layout.tsx
  src/app/review/[[...storeId]]/page.tsx
  src/app/review/[storeId]/page.tsx
  src/app/terms/page.tsx
  src/components/common/FixedBottomCTAButton/index.tsx
  src/components/review/ImageUploader/index.tsx
  src/components/review/VisitDate/index.tsx
  src/hooks/api/useGetPresignedUrl.ts
  src/hooks/api/usePostLog.ts
  src/hooks/api/useUploadImageToNCloud.ts
Labels: feat

#127 리뷰 페이지 수정
  src/app/review/[[...storeId]]/page.tsx
  src/components/review/ImageUploader/index.tsx
Labels: fix

#124 마이페이지 작성
  public/assets/ddobab/ddobab_default_0_s.svg
  public/assets/ddobab/ddobab_default_1_s.svg
  public/assets/ddobab/ddobab_default_2_s.svg
  public/assets/ddobab/ddobab_default_3_s.svg
  public/assets/icon24/trash_24.svg
  public/assets/image/mypage/background.png
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/DeleteTrashButton/index.tsx
  src/components/common/ListItem/index.tsx
  src/components/main/LogItem/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
  src/components/mypage/BookMarkContent/index.tsx
  src/components/mypage/BookmarkItem/index.tsx
  src/components/mypage/Log/index.tsx
  src/components/mypage/MyLogContent/index.tsx
  src/components/mypage/Tab/TabItem.tsx
  src/components/search/SearchItem/index.tsx
  src/constants/mypage.ts
  src/hooks/api/useDeleteLog.ts
  src/hooks/api/useGetUserProfile.ts
  src/hooks/api/useInfiniteBookMark.ts
  src/hooks/api/useInfiniteMyLog.ts
  src/hooks/api/usePatchBookmark.ts
  src/hooks/api/usePutUserName.ts
Labels: feat

#123 인증, 인가 로직 작성
  .pnp.cjs
  .yarn/cache/@types-js-cookie-npm-3.0.6-c9126e5b48-272d551687.zip
  .yarn/cache/js-cookie-npm-3.0.5-8fc8fcc9b4-2dbd2809c6.zip
  package.json
  src/api/api-config.ts
  src/app/auth/page.tsx
  src/app/login/page.tsx
  src/app/terms/page.tsx
  src/constants/endpoint.ts
  src/hooks/api/usePostSignUp.ts
  src/middleware.ts
  src/utils/getTokenRefresh.ts
  yarn.lock
Labels: feat

#131 검색 페이지 로직 수정
  src/app/search/page.tsx
  src/components/search/SearchItem/index.tsx
  src/hooks/api/useGetStoreList.ts
Labels: fix

#118 음식점 상세 페이지 구현
  src/components/common/ImageContainer/index.tsx
  src/components/main/LogItem/index.tsx
  src/components/main/StoreDetailSection/Content/index.tsx
  src/components/main/StoreDetailSection/Report/ReVisit.tsx
  src/components/main/StoreDetailSection/Report/TopVisit.tsx
  src/components/main/StoreDetailSection/Report/index.tsx
  src/components/main/StoreDetailSection/Reviews/index.tsx
  src/components/main/StoreDetailSection/SectionTitle/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
  src/hooks/api/useGetReport.ts
  src/hooks/api/useInfiniteReview.ts
Labels: feat

#139 리뷰 작성 로직 수정, 리뷰 작성 완료 페이지 작성
  public/assets/ddobab/ddobab_writing.svg
  src/app/review/[[...storeId]]/layout.tsx
  src/app/review/complete/page.tsx
  src/app/review/page.tsx
  src/components/main/AddStoreButton/index.tsx
  src/hooks/api/usePostLog.ts
Labels: feat, refactor

#143 fix: script 태그 사용
  src/app/layout.tsx
Labels: fix

#136 리뷰페이지로 데이터 전송
  public/assets/ddobab/ddobab_writing.svg
  src/app/page.tsx
  src/app/review/[[...storeId]]/layout.tsx
  src/app/review/[[...storeId]]/page.tsx
  src/app/review/complete/page.tsx
  src/app/review/page.tsx
  src/app/search/page.tsx
  src/components/main/AddStoreButton/index.tsx
  src/components/main/LocationStorePinList/index.tsx
  src/components/main/StorePreviewSection/index.tsx
  src/components/main/WriteLogButton/index.tsx
  src/hooks/api/useGetPinList.ts
  src/hooks/api/usePostLog.ts
  src/types/map.ts
Labels: feat

#146 fix script
  src/app/layout.tsx
Labels: fix

#141 Feature/#140
  public/assets/icon16/arrow_square_16.svg
  public/assets/icon24/right_arrow_24.svg
  src/api/api-config.ts
  src/app/settings/layout.tsx
  src/app/settings/page.tsx
  src/constants/endpoint.ts
  src/constants/settings.ts
  src/hooks/api/useLogout.ts
  src/middleware.ts
  src/utils/auth.ts
Labels: feat

#162 풀 바텀싯 연동 및 북마크 기능 작성
  next.config.js
  src/app/page.tsx
  src/components/common/Header/index.tsx
  src/components/main/BookMarkPinList/index.tsx
  src/components/main/BottomSheet/components/BottomSheetWrapper.tsx
  src/components/main/BottomSheet/contexts/BottomSheetContext.tsx
  src/components/main/LocationStorePinList/index.tsx
  src/components/main/StoreDetailSection/Content/index.tsx
  src/components/main/StoreDetailSection/Report/ReVisit.tsx
  src/components/main/StoreDetailSection/Report/TopVisit.tsx
  src/components/main/StoreDetailSection/index.tsx
  src/components/main/StorePreviewSection/index.tsx
  src/hooks/api/useGetPinList.ts
  src/hooks/api/useGetReport.ts
  src/hooks/api/useGetStore.ts
  src/hooks/api/usePatchBookmark.ts
Labels: feat

#142 마이 페이지 입력값 글자 수 제한 수정
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/main/StoreDetailSection/Report/index.tsx
Labels: fix

#168 리뷰 남기기 분기처리
  src/components/main/WriteLogButton/index.tsx
Labels: fix

#170 핀 버블 분기처리
  src/components/common/Pin/PinBubble.tsx
Labels: fix

#174 음식점명 안넘어가는 버그 수정
  src/app/page.tsx
  src/components/main/StorePreviewSection/index.tsx
Labels: fix

#172 #171 feat: 첫 방문시 리포트 컴포넌트 0명 표기
  src/components/main/StoreDetailSection/Report/ReVisit.tsx
  src/components/main/StoreDetailSection/Report/TopVisit.tsx
Labels: fix

#176 #175 fix: 첫 방문 시 리뷰 요청 취소
  src/hooks/api/useInfiniteReview.ts
Labels: fix

#179 DB에 있는 식당 리뷰페이지 이동시 storeId 전달
  src/components/main/WriteLogButton/index.tsx
Labels: fix

#181 storeId 분기처리
  src/app/review/page.tsx
Labels: fix

#184 fix : 또잇 리포트 응답값 안나오는 거 수정
  src/hooks/api/useGetReport.ts
Labels: fix

#186 음식점 상세 페이지 이미지 오류들 수정
  src/components/main/StoreDetailSection/index.tsx
  src/hooks/api/useGetReport.ts
Labels: fix

#189 fix: 북마크, 내로그 요청 기본 값 변경
  src/hooks/api/useInfiniteBookMark.ts
  src/hooks/api/useInfiniteMyLog.ts
Labels: fix

#191 핀 안받아와지는 버그 수정
  src/app/page.tsx
Labels: fix

#193 fix mutate
  src/app/layout.tsx
  src/app/page.tsx
  src/hooks/api/useGetPinList.ts
Labels: fix

#187 middleware 수정
  src/api/api-config.ts
  src/app/mypage/layout.tsx
  src/app/review/page.tsx
  src/components/common/Header/index.tsx
  src/middleware.ts
Labels: fix

#194 fix mutate rollback
  src/app/page.tsx
  src/hooks/api/useGetPinList.ts
Labels: fix

#196 #195 fix : 북마크 삭제 시 storeId 변경
  src/components/mypage/BookMarkContent/index.tsx
  src/components/mypage/BookmarkItem/index.tsx
  src/hooks/api/usePatchBookmark.ts
Labels: fix

#198 fix : 리뷰 기본값 변경
  src/hooks/api/useInfiniteReview.ts
Labels: fix

#204 이미지 로딩 관련 수정
  src/components/common/ImageContainer/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
Labels: fix

#202 Bugfix/middleware
  src/api/api-config.ts
  src/app/review/page.tsx
  src/app/settings/page.tsx
  src/middleware.ts
  src/utils/auth.ts
Labels: fix

#205 fix: 무한스크롤 수정
  src/components/main/StoreDetailSection/Reviews/index.tsx
  src/components/mypage/BookMarkContent/index.tsx
  src/components/mypage/MyLogContent/index.tsx
Labels: fix

#207 fix mutation observer
  src/components/main/BottomSheet/components/BottomSheetFullContent.tsx
Labels: fix

#209 Bugfix/#208
  src/api/api-config.ts
  src/app/search/page.tsx
  src/components/mypage/Log/index.tsx
  src/hooks/api/useLogout.ts
  src/hooks/api/usePostWithdraw.ts
  src/utils/auth.ts
Labels: fix

#211 바텀싯 강제로 땡겨올리면 뒤의 지도가 노출되는 버그 수정
  src/components/main/BottomSheet/components/BottomSheetWrapper.tsx
Labels: fix

#212 바텀싯 가끔 높이 이상한 버그 수정
  src/components/main/BottomSheet/components/BottomSheetShowContent.tsx
Labels: fix

#213 아이폰 인풋 포커스시 확대 안되도록 수정
  src/app/layout.tsx
Labels: fix

#215 #192 feat: 로그아웃, 회원 탈퇴 시 쿠키 날린 거 앱으로 전달하는 로직 추가
  src/constants/postmessage.ts
  src/hooks/useWebView.ts
  src/utils/auth.ts
Labels: feat

#218 fix: ReactNativeWebview 일때만 postMessage 보내도록 수정
  src/utils/auth.ts
Labels: fix

#219 QA 건 수정
  src/app/mypage/page.tsx
  src/app/review/page.tsx
  src/components/main/CurrentLocationButton/index.tsx
  src/components/main/ProfileButton/index.tsx
  src/components/main/WriteLogButton/index.tsx
  src/components/review/VisitDate/index.tsx
Labels: fix
