Repository depromeet/ddoeat_client, pull requests merged in 2024-02, with the labels that each got.

#223 fix : 또잇 리포트 넓이 수정
  src/components/main/StoreDetailSection/Report/ReportContainer.tsx
  src/components/main/StoreDetailSection/Report/index.tsx
Labels: fix

#225 #224 fix: video tag에 playsinline 추가
  src/components/onboarding/Scene/index.tsx
Labels: fix

#231 Fix/#229
  src/app/login/page.tsx
  src/app/review/page.tsx
  src/components/common/Modal/index.tsx
  src/components/review/VisitDate/index.tsx
  src/components/terms/TermsItem/index.tsx
Labels: fix

#235 fix: 리뷰 페이지 이동 조건 수정
  src/app/page.tsx
  src/components/main/WriteLogButton/index.tsx
  src/hooks/api/useDeleteLog.ts
Labels: fix

#237 #236 refactor: gif 로드 후 모달 나오게 수정
  src/components/onboarding/Scene/index.tsx
Labels: refactor

#240 음식점 상세 페이지, 마이페이지 QA
  public/assets/ddobab/ddobab_report_2.svg
  src/app/mypage/page.tsx
  src/components/mypage/BookMarkContent/index.tsx
Labels: fix

#249 애플 로그인 구현
  global.d.ts
  src/api/apple-config.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/utils/generateNonce.ts
Labels: feat

#247 마이페이지 디자인 수정
  public/assets/image/mypage/background.png
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/mypage/BookMarkContent/index.tsx
  src/components/mypage/MyLogContent/index.tsx
Labels: fix

#254 카카오 로그인 REST 방식으로 로직 수정
  src/app/login/page.tsx
  src/middleware.ts
Labels: refactor

#246 imageUrl uuid 계산 로직 수정
  src/app/review/page.tsx
Labels: fix

#245 엔터 키 입력 시 검색되도록 로직 수정
  src/app/search/page.tsx
  src/components/search/SearchTopBar/index.tsx
Labels: fix

#263 애플 로그인 시 auth 페이지에 머물도록 수정
  src/app/auth/page.tsx
  src/middleware.ts
Labels: fix

#264 id_token params로 넘기도록 수정
  src/middleware.ts
Labels: fix

#265 애플 로그인 커스텀 이벤트 생성
  src/app/auth/page.tsx
  src/app/login/page.tsx
  src/middleware.ts
Labels: fix

#266 애플 로그인 정보 스토리지 저장
  src/app/login/page.tsx
  src/components/common/AppleProvider/index.tsx
Labels: fix

#267 redirect uri 변경
  src/components/common/AppleProvider/index.tsx
Labels: fix

#268 login 페이지로 리다이렉트하도록 수정
  src/app/login/page.tsx
  src/components/common/AppleProvider/index.tsx
  src/middleware.ts
Labels: fix

#269 popup option 수정
  src/app/login/page.tsx
  src/components/common/AppleProvider/index.tsx
  src/middleware.ts
Labels: fix

#271 script 위치 수정
  src/app/layout.tsx
  src/middleware.ts
Labels: fix

#272 redirectURI 타입 수정
  global.d.ts
Labels: fix

#273 로그인 api 로직 추가
  global.d.ts
  src/app/login/page.tsx
  src/hooks/api/useAppleLogin.ts
  src/types/apple.ts
Labels: fix

#275 data log 추가
  src/app/login/page.tsx
Labels: fix

#276 middleware login 삭제
  src/middleware.ts
Labels: fix

#279 post 로직으로 수정
  src/app/login/page.tsx
  src/hooks/api/useAppleLogin.ts
Labels: fix

#280 preventDefault 코드 추가
  src/app/login/page.tsx
Labels: fix

#281 카카오 로그인 POST 방식으로 수정
  src/middleware.ts
Labels: fix

#282 애플 로그인 요청 로직 수정
  src/app/login/page.tsx
  src/hooks/api/useAppleLogin.ts
Labels: fix

#283 애플 로그인 호출 삭제
  src/app/login/page.tsx
Labels: fix

#285 useEffect 훅 로직 삭제
  src/app/login/page.tsx
Labels: fix

#286 useEffect 훅 내부 로직 수정
  src/app/login/page.tsx
Labels: fix

#287 fetch 방식으로 변경
  src/app/login/page.tsx
Labels: fix

#288 api 주소 수정
  src/app/login/page.tsx
Labels: fix

#289 토큰 저장 및 리다이렉트 로직 추가
  src/app/login/page.tsx
Labels: feat

#290 interceptor 로직 수정
  src/api/api-config.ts
Labels: fix

#248 리드미 틀잡기
  README.md
Labels: docs

#292 이미지 업로드 이슈 수정
  src/api/api-config.ts
Labels: fix

#296 400 -> 401로 로직 수정
  src/api/api-config.ts
Labels: fix

#297 return 문 추가
  src/api/api-config.ts
Labels: fix

#257 신고 기능 토스트 추가
  src/components/common/DeleteTrashButton/index.tsx
  src/components/common/ListItem/index.tsx
  src/components/common/Modal/index.tsx
  src/components/main/LogItem/index.tsx
  src/components/main/StoreDetailSection/Reviews/ReportButton/index.tsx
  src/components/main/StoreDetailSection/Reviews/index.tsx
  src/components/main/StoreDetailSection/StoreDetailLog/index.tsx
  src/components/review/TextArea/index.tsx
  src/types/modal.ts
Labels: feat

#294 #293 docs: update README.md
  README.md
Labels: docs

#298 로직 위치 변경
  src/api/api-config.ts
Labels: fix

#299 로그인버튼 active 컬러 수정
  src/app/login/page.tsx
Labels: style

#301 fix : 로그 삭제 시 리포트, 리뷰, 프로필 불러오기
  src/hooks/api/useDeleteLog.ts
Labels: fix

#307 바텀싯 상세에서 뒤로가기 누르면 내려가도록 수정
  src/components/main/StoreDetailSection/index.tsx
Labels: fix

#303 fix : 음식점 상세 페이지 로그 불러오기
  src/hooks/api/usePostLog.ts
Labels: fix

#305 fix : storeId 수정
  src/components/main/StoreDetailSection/index.tsx
Labels: fix

#309 공유기능 작성
  public/assets/icon24/share_24.svg
  src/api/api-config.ts
  src/app/login/page.tsx
  src/app/mypage/layout.tsx
  src/app/page.tsx
  src/app/share/[id]/page.tsx
  src/app/share/layout.tsx
  src/components/main/BottomSheet/components/BottomSheetShowContent.tsx
  src/components/share/SharingSpotPinList/index.tsx
  src/constants/endpoint.ts
  src/hooks/api/useGetSharingSpot.ts
  src/hooks/api/useGetUserProfile.ts
  src/hooks/useCoordinate.ts
  src/utils/copyToClipboard.ts
Labels: feat

#310 공유시 지도 범위 지정
  src/app/share/[id]/page.tsx
Labels: fix, feat
